kiosk:
  environment: prod
  service:
    PipelineService:
      workers: 10
      autostart: true

spring:
  datasource:
    poolName: Kiosk.CP
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://kiosk.cwj11t2vidmo.us-east-1.rds.amazonaws.com:3306/kiosk
    username: kioskadmin
    password: kioskadmin

